services:
  postgres:
    image: postgres:16
    container_name: morpheus-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      # This binds the port only to the host's localhost interface for better security.
      # It prevents the database from being exposed to the public internet.
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    volumes:
      - morpheus_pg_data:/var/lib/postgresql/data
      # This line mounts the init.sql script to be run on first-time creation.
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: morpheus-backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT}:9000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - PORT=9000
      # Pass other necessary environment variables from a .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USE_OPENAI=${USE_OPENAI}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - GOOGLE_GEOCODING_API_KEY=${GOOGLE_GEOCODING_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_WEB_APP_URL=${TELEGRAM_WEB_APP_URL}
      # --- Development/Production Settings ---
      - NODE_ENV=${NODE_ENV:-production}
      - DOCKER_ENV=true
      - DANGEROUSLY_BYPASS_AUTH=${DANGEROUSLY_BYPASS_AUTH:-false}
      - DATABASE_TYPE=${DATABASE_TYPE:-postgres}
      - USE_MOCK_API=${USE_MOCK_API:-false}

  frontend:
    build:
      context: ./frontend
      args:
        VITE_GOOGLE_PLACES_API_KEY: ${VITE_GOOGLE_PLACES_API_KEY}
    container_name: morpheus-frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend

volumes:
  morpheus_pg_data:
